### ISSUE TITLE
Avro Union

### ISSUE THREAD

**Issue by wgriffiths** [karrick/goavro#13]
I am trying to use the Avro Union type but I get the following error.

```bash
Schema Error - Record "uk.co.tbp.Order" field "sourceOrderID": default value ought to encode using field schema: cannot encode binary null: expected: Go nil; received: string
```
This is my code, probably doing something stupid. 

```go
package main

import (
	"fmt"

	"github.com/karrick/goavro"
)

const simpleSchema = `
{
  "type": "record",
  "name": "Order",
  "doc:": "Command to create a new order.",
  "namespace": "uk.co.tbp",
  "fields": [{
      "name": "sourceOrderID",
      "type": ["null","long"],
       "default": "null"
    }
  ]
}
`

func main() {
	_, err := goavro.NewCodec(simpleSchema)

	if err != nil {
		fmt.Printf("Schema Error - %s", err)
	}

}
```

**Comment by karrick** [comment]
@wgriffiths,

It is a minor mistake, one easy to correct, and I'm happy to help! Half of the answer is with the schema you provided. The other half will be an advisory note for when you start encoding data.

First of all, when specifying the data type, you correctly used quotations around the `null` alongside the `long` in the Avro union. That's important, because all primitive data *types* must be in quotations when used to declare them. However, when you specify the default *value* for that data type, if it cannot be quoted, because it is the null _value_. If you remove the quotes around the default value `null`, your schema compiles just fine.

This odd requirement is not `goavro` specific, but Avro schema specific. Let me provide an additional example. Let's say we had another field in that record with a type `["long", "string"]` and we wanted to provide a default value for it. We know the data type for the default would have to match the first data type in the union. We would have to specify the value as `"default": 13`, *not* `"default": "13"`.

```Go
package main

import (
	"fmt"
	"log"

	"github.com/karrick/goavro"
)

const simpleSchema = `
{
  "type": "record",
  "name": "Order",
  "doc:": "Command to create a new order.",
  "namespace": "uk.co.tbp",
  "fields": [{
      "name": "sourceOrderID",
      "type": ["null","long"],
       "default": null
    },
    {
      "name": "example",
      "type": ["long","string"],
       "default": 13
    }
  ]
}
`

func main() {
	codec, err := goavro.NewCodec(simpleSchema)
	if err != nil {
		log.Fatalf("cannot compile: %s", err)
	}
	native, _, err := codec.NativeFromTextual([]byte("{}"))
	if err != nil {
		log.Fatalf("cannot decode: %s", err)
	}
	fmt.Printf("%v\n", native)
}
```

Okay, the next part of my answer is specific to `goavro` library use. When you run the example code above, the output is `map[sourceOrderID:<nil> example:map[long:13]]`. There are a couple of things worth noting: First, we decoded an empty JSON object into a Go native map, with two fields. Each field has the default value, because the input JSON object had no properties, and the `goavro` library put the default values into the Go map.

Second, and this is the big concept here: the union value `null` is represented as a Go `nil`, while any other union value is represented as a map, with the key being the type name of the data, and its value being the actual data value. In the above example, the field `example` has a data type that is a map with a single key-value pair. The key is the string `long` which matches the data type, and that key's value is `13`.

The Avro specification states that when encoding or decoding JSON values, if the value is `null` it can be directly represented as a JSON `null` value. But if one of the other data types, a decoder will have to one day deduce the data type of the value when it has several choices to make. So the Avro specification says to encode another JSON object in there with a single key-value pair, and where the name of the key is the textual name of the data type, and its value is the actual value. `goavro` adheres to this model, and encodes from and decodes to Go native types that mirror this expectation.

Here's an example of what I mean:

```Go
package main

import (
	"fmt"
	"log"

	"github.com/karrick/goavro"
)

const simpleSchema = `
{
  "type": "record",
  "name": "Order",
  "doc:": "Command to create a new order.",
  "namespace": "uk.co.tbp",
  "fields": [{
      "name": "sourceOrderID",
      "type": ["null","long"],
       "default": null
    },
    {
      "name": "example",
      "type": ["long","string"],
       "default": 13
    }
  ]
}
`

func main() {
	codec, err := goavro.NewCodec(simpleSchema)
	if err != nil {
		log.Fatalf("cannot compile: %s", err)
	}
	native := map[string]interface{}{
		"sourceOrderID": nil,
		"example":       goavro.Union("string", "someString"),
	}
	textual, err := codec.TextualFromNative(nil, native)
	if err != nil {
		log.Fatalf("cannot decode: %s", err)
	}
	fmt.Printf("%s\n", textual)
}
```

The output of this program is `{"sourceOrderID":null,"example":{"string":"someString"}}`.

I hope I've answered your questions about using `goavro` to encode and decode Avro unions, both with and without default values. If you have additional questions, please re-open the bug and I will attempt to address them.

**Comment by wgriffiths** [comment]
Sorry for the stupid mistake. Thank you so much for your quick and detailed response.
