### ISSUE TITLE
wrong decoded value with nullable fields?

### ISSUE THREAD

**Issue by quipo** [karrick/goavro#3]
Given this field definition in an Avro schema:
```
{
  "type": "record",
  "name": "XXX",
  "namespace": "com.mycompany",
  "fields": [
    {
      "name": "auditHeader",
      "type": {
        "type": "record",
        "name": "AuditHeader",
        "namespace": "com.mycompany.events",
        "fields": [
          {
            "name": "instance",
            "type": [
              "null",
              "string"
            ]
          }
        ]
      }
    }
  ]
}
```

and decoding binary avro into a go map (using `codec.NativeFromBinary(buf)`), I get 

```
map[string]interface {}{
	"auditHeader": map[string]interface {}{
		"instance":map[string]interface {}{"string":"_"}
	}
}
``` 

whereas I'd expect to see

```
map[string]interface {}{
	"auditHeader": map[string]interface {}{
		"instance":"_"
	}
}
```

Similarly, given this avro schema:
```
{
  "type": "record",
  "name": "Test",
  "namespace": "com.mycompany",
  "fields": [
    {
      "name": "someNames",
      "type": [
        "null",
        {
          "type": "array",
          "items": {
            "type": "record",
            "name": "MyRecord",
            "fields": [
              {
                "name": "name",
                "type": "string"
              },
              {
                "name": "nameLocale",
                "type": "string"
              }
            ]
          }
        }
      ]
    }
  ]
}
```

I get 

```
map[string]interface {}{
  "someNames": map[string]interface {}{
    "array":[]interface {}{
      map[string]interface {}{
        "nameLocale":"en_US",
        "name":"Some Name"
      }
    }
  }
}
```

whereas I'd expect to get

```
map[string]interface {}{
  "someNames": []interface {}{
    map[string]interface {}{
      "nameLocale":"en_US",
      "name":"Some Name"
    }
  }
}
```

**Comment by karrick** [comment]
@quipo,

Thank you for reporting this behavior, but it's as intended and documented in the README.md file for the project.

> Because of encoding rules for Avro unions, when an union's value is
> `null`, a simple Go `nil` is returned. However when an union's value
> is non-`nil`, a Go `map[string]interface{}` with a single key is
> returned for the union. The map's single key is the Avro type name and
> its value is the datum's value.

The reason for this choice is threefold.

First, goavro returns native Go data structures that mirror the exact structure that Avro JSON encoding describes. This simplifies expectations. When you translate data between JSON and Go, the same exact hierarchy is returned, although one is in JSON format and the other in native Go data types.

The second and third reasons are code clarity and performance. Prior to tag v0.0.2 of the goavro rewrite, goavro would use reflection when encoding a datum to a union. While the code was functional, it lacked clarity, and it was significantly less performant due to the reflection checks. Tag v0.0.2 changed the logic, and had the encoder require the input data structure to look like Avro JSON encoding, and the decoder would return a data structure that looked like Avro JSON encoding. The change improved code clarity, and improved performance by three times.

When decoding data, or rather calling `NativeFrom(Binary|Textual)`, the upstream code needs to know the underlying data type of the decoded value. If the data were unboxed, the upstream code would have to use reflection, and then perform a type assertion to get the concrete value. However what if a value was a union of either of `bytes` or `{"name":"f4","type":"fixed","size":4}`? Reflection would tell the upstream that it had a slice of bytes, `[]byte`, but not whether it was `fixed` or `bytes`. What if the decoded data happened to be `bytes` but exactly 4 bytes long, which matched the `f4` definition? Or, what if there were multiple `fixed` types declared in the Avro schema? Having the boxed version sends a signal to the upstream of the concrete data type in the form of the map key, which in this example would be either `bytes` or `f4`.

While performance ought never be the primary driver in algorithm selection, it is the second most important driver after correctness. In this case, having the Codec return a native Go data structure that mirrored the Avro JSON encoding seemed like a win. Having the union implementation source code be more clear seemed like a win. And having a 3x performance improvement in encoding seemed like a win.

So what are the tradeoffs? Essentially along with the API difference between the original goavro code and the new engine's API, the new goavro engine requires boxing datum values that are a union type, and unboxing that datum when decoding from a union. But I believe I've demonstrated above that such a requirement can actually not only clean up the goavro source code, but upstream source code which uses goavro. I hope my examples were able to convey that.

Significant time was spent all through the new engine to reduce the amount of boxing of data types when using the new engine, and the benefits of that time and energy are apparent as I use the newer engine. However the three reasons above, especially the source code clarity outlines above, seemed reason enough for the special case for handling unions. Indeed, the Avro specification describes the exact same manner of encoding and decoding using JSON to get around the same problems. I thought it a natural solution to adopt here as well.

From the Avro specification:

> The value of a union is encoded in JSON as follows:
> 
> * if its type is null, then it is encoded as a JSON null;
> 
> * otherwise it is encoded as a JSON object with one name/value
>   pair whose name is the type's name and whose value is the
>   recursively encoded value. For Avro's named types (record,
>   fixed or enum) the user-specified name is used, for other types
>   the type name is used.
> 
> For example, the union schema ["null","string","Foo"], where Foo
> is a record name, would encode:
> 
> * null as null;
> * the string "a" as {"string": "a"}; and
> * a Foo instance as {"Foo": {...}}, where {...} indicates the
>   JSON encoding of a Foo instance.

**Comment by quipo** [comment]
thanks a lot for the detailed explanation, I had missed that paragraph in the README. 

From a technical point of view, it makes sense.

I'm thinking whether this is the best way to implement this, though, from the user's perspective.  I totally understand that UNIONs present a problem that can be at times really difficult to solve, and I don't necessarily have a better idea, but observing the resulting Go map, I can't help but think that some critical type information is lost. 

Without keeping the Avro schema in mind when reading the Go map, there's no way of knowing that the field called "string" is really just a type wrapper, and not actual payload.  In other words, i feels like the decoding action requires a "second pass" that is left to the client.  And the Avro schema is required again when traversing the Go map, because there's no other type hint inside the Go map that might indicate that a certain field still needs to be (un)boxed. That information is only given by the Avro schema itself, but is lost in the Go map. So in a way (playing devil's advocate here), a 2x perf improvement in decoding the Avro binary might be offset by the need to do a 2nd pass on the client side, where the Avro decoder likely needs to be wrapped by another "decoder" which makes decisions over the fields left "boxed" by the Avro decoder.

The Avro spec you quoted above seems a bit odd to me in this regard. I'm sure there are good reasons to have this behaviour, but it's still confusing.  In non-very-technically-accurate language, both Go maps and JSON docs have a "loosely typed" schema (e.g. as opposed to a `struct`), which easily adapts to individual fields to have different types (and accommodate one of the N possible values of an UNION). So the behaviour of *decoding* an object to a JSON doc or a Go map should be pretty straightforward IMHO.   The inverse (i.e. encoding to an Avro binary) or decoding Avro to a `struct` might not be true.

Thoughts?

**Comment by karrick** [comment]
> I can't help but think that some critical type information is lost.

I have to take a disagree with you about type information being lost. With the method described by the Avro specification used in JSON encoding, the same method that goavro uses when decoding either JSON or binary to native Go data types, the type information _is_ there in the decoded data, in the form of the map key name.

> Without keeping the Avro schema in mind when reading the Go map,
> there's no way of knowing that the field called "string" is
> really just a type wrapper

In accordance with the Avro spec, every union is encoded the same way: when `null` is encoded, it is simply encoded as a `nil` in Go. For all other cases every union is encoded as a JSON object with a single key-value tuple. In the same way, every union is decoded as a Go map with a single key-value tuple. If a particular schema is a union, then it is always encoded and decoded with a box, with the map key being the name of the type of the actual data.

Using the decoded union's data value does not require a second pass; it requires unboxing the value. It does require upstream source code to actually unbox the value. But no second passes must be made over the data.

> And the Avro schema is required again when traversing the Go map,
> because there's no other type hint inside the Go map that might
> indicate that a certain field still needs to be (un)boxed.

Partially correct: as described in the Avro specification, the writer schema is always required when reading the data. Knowledge of the write schema coupled with the type hint in the form of the map key provides all the information that upstream would need to use the data.

I think that a project might be able to more closely deliver what you expect if it were to generate Go code to translate data from one format to another. The other possibility is using structure tags to decode binary or textual Avro data directly to Go data structures in the upstream source code, and vice versa, but then it would use a tremendous amount of reflection to do so, causing performance to suffer.

Here's an example of one way to handle decoding union values.

https://github.com/karrick/goavro/blob/master/union_test.go#L168

Without the type information provided by the box, I'm curious what the source code would look like when handling the union's value. I think it would be more complex, involving reflection, at the least. And if there were user defined named types in the schema, and they were possible union data types, the complexity would explode.

I agree the code is not pretty. It sure isn't minimalistic. But how else would the upstream code handle the variety of different types that the union value could be?

**Comment by quipo** [comment]
Fair enough :-)   Thanks again for the detailed answer, I really appreciate it
