### ISSUE TITLE
Another fuzz panic

### ISSUE THREAD

**Issue by thomasdesr** [karrick/goavro#5]
If the blockCount ends up the max negative int64, when we run `blockCount = -blockCount` it will still be negative

```golang
if blockCount < 0 {
    // NOTE: A negative block count implies there is a long encoded block
    // size following the negative block count. We have no use for the block
    // size in this decoder, so we read and discard the value.
    blockCount = -blockCount // convert to its positive equivalent <-- This doesn't quite work
    if _, err = longBinaryReader(br); err != nil {
        return nil, fmt.Errorf("cannot decode Map block size: %s", err)
    }
}
```

Reproduction steps
```golang
package main

import (
    "strings"

    "github.com/karrick/goavro"
)

func main() {
    goavro.NewOCFReader(strings.NewReader("Obj\x01\xff\xff\xff\xff\xff\xff\xff\xff\xff\x010"))
}
```

or in fuzz.go:

```diff
diff --git a/fuzz_test.go b/fuzz_test.go
index da2fab3..04173e4 100644
--- a/fuzz_test.go
+++ b/fuzz_test.go
@@ -97,6 +97,7 @@ func TestCrashers_OCF_e2e(t *testing.T) {
                        "\x00\x00\x00\x00\x00\x00\x11\"\t\x10\x90\x04\x16TEST_ST" +
                        "R123\x00\x04\x00\x02S\xfeJ\x17\u007f\xb4r\x11\x0e\x96&\x0e" +
                        "\xda<\xed\x86\xf6",
+               "map: initialSize overflow-2": "Obj\x01\xff\xff\xff\xff\xff\xff\xff\xff\xff\x010",
                "array: initialSize overflow": "Obj\x01\x04\x14avro.codec\bnul" +
                        "l\x16avro.schema\xa2\x0e{\"typ" +
                        "e\":\"record\",\"name\":\"" +
```

Ideas:
* Check is to see if blockSize is math.MinInt64 and just abort pre-allocation (`blockCount = 0`)
* Abort pre-allocation on any negative values
* Stop pre-allocating at all (and remove this check), until perf requires it

**Comment by karrick** [comment]
I love you, @thomaso-mirodin! Thanks for opening up this issue! 👍

**Comment by karrick** [comment]
Good ideas about resolving the issue. Sadly whether we pre-allocate or not doesn't change the fact that when reading either an array or a map, the binary data includes blockCounts in front of every block, which legally may be negative. While the spec says to take the negative of the negative to get the actual block count, I don't think they were worried about implementation details when the block count was so large it would always be negative due to how computers store signed integers. Example, when only 8 bits, you can go from -128 to 127. And -(-128) == -128.

https://play.golang.org/p/3NMh1x6z4K

I think the best way is to abort processing in some way when this happens, but happy to entertain better suggestions.
